--------------------------------------------------------
--  Fichier créé - mercredi-avril-28-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ACTIVITE
--------------------------------------------------------

  CREATE TABLE "SOUMAYA"."ACTIVITE" 
   (	"ID" NUMBER, 
	"NOM_ACTIVITE" VARCHAR2(20 BYTE), 
	"DAT" VARCHAR2(20 BYTE), 
	"DUREE" NUMBER, 
	"TYPE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ANIMAL
--------------------------------------------------------

  CREATE TABLE "SOUMAYA"."ANIMAL" 
   (	"ID" NUMBER, 
	"AGE" NUMBER, 
	"PRIX" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"RACE" VARCHAR2(20 BYTE), 
	"SEX" VARCHAR2(20 BYTE), 
	"DATE_ACHAT" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table BOUTIQUE
--------------------------------------------------------

  CREATE TABLE "SOUMAYA"."BOUTIQUE" 
   (	"ID" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"ADR" VARCHAR2(20 BYTE), 
	"TEL" NUMBER, 
	"MAIL" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ENFANT
--------------------------------------------------------

  CREATE TABLE "SOUMAYA"."ENFANT" 
   (	"ID" NUMBER, 
	"NOM_PRENOM" VARCHAR2(20 BYTE), 
	"ETAT_PSYCOLOGIQUE" VARCHAR2(20 BYTE), 
	"TALENT" VARCHAR2(20 BYTE), 
	"SEXE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ETUDIANT
--------------------------------------------------------

  CREATE TABLE "SOUMAYA"."ETUDIANT" 
   (	"ID" VARCHAR2(20 BYTE), 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table FICHE_ANIMAL
--------------------------------------------------------

  CREATE TABLE "SOUMAYA"."FICHE_ANIMAL" 
   (	"ID" NUMBER, 
	"POID" NUMBER, 
	"TAILLE" NUMBER, 
	"NBR_CONSULTATION" NUMBER, 
	"ID_ANNIMAL" NUMBER, 
	"DATE_VACC" VARCHAR2(20 BYTE), 
	"ETAT" VARCHAR2(20 BYTE), 
	"NOM_MALADE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table FOURNITURE
--------------------------------------------------------

  CREATE TABLE "SOUMAYA"."FOURNITURE" 
   (	"ID" VARCHAR2(20 BYTE), 
	"REF" VARCHAR2(20 BYTE), 
	"QUANTITE" VARCHAR2(20 BYTE), 
	"PRIX" NUMBER, 
	"DAT" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table INGR
--------------------------------------------------------

  CREATE TABLE "SOUMAYA"."INGR" 
   (	"NOMING" VARCHAR2(20 BYTE), 
	"TYPE" VARCHAR2(20 BYTE), 
	"VALEUR_ALIMENTAIRE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table INGREDIENT
--------------------------------------------------------

  CREATE TABLE "SOUMAYA"."INGREDIENT" 
   (	"NOM_R" VARCHAR2(20 BYTE), 
	"TYPE_R" VARCHAR2(20 BYTE), 
	"HEURE_R" VARCHAR2(20 BYTE), 
	"CATEGORIE_R" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MEDICAMENT
--------------------------------------------------------

  CREATE TABLE "SOUMAYA"."MEDICAMENT" 
   (	"ID" NUMBER, 
	"QUANTITE" NUMBER, 
	"DAT" VARCHAR2(20 BYTE), 
	"PRIX" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PRESTATAIRE
--------------------------------------------------------

  CREATE TABLE "SOUMAYA"."PRESTATAIRE" 
   (	"IDPRES" NUMBER, 
	"NOMPRES" VARCHAR2(20 BYTE), 
	"PRENOMPRES" VARCHAR2(20 BYTE), 
	"SALAIREPRES" NUMBER, 
	"SPECIALITEPRES" VARCHAR2(20 BYTE), 
	"DATEEMBAUCHEPRES" VARCHAR2(20 BYTE), 
	"NBR_HEURESPRES" NUMBER, 
	"TELPRES" NUMBER, 
	"ADRESSEPRES" VARCHAR2(20 BYTE), 
	"SEXEPRES" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SUIVI
--------------------------------------------------------

  CREATE TABLE "SOUMAYA"."SUIVI" 
   (	"ID" NUMBER, 
	"TAILLE" NUMBER, 
	"POID" NUMBER, 
	"TENSION" NUMBER, 
	"DAT" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table VETEMENT
--------------------------------------------------------

  CREATE TABLE "SOUMAYA"."VETEMENT" 
   (	"REF" NUMBER, 
	"SAISON" VARCHAR2(20 BYTE), 
	"GENRE" VARCHAR2(20 BYTE), 
	"TYPE" VARCHAR2(20 BYTE), 
	"TAILLE" VARCHAR2(20 BYTE), 
	"MARQUE" VARCHAR2(20 BYTE), 
	"PRIX" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SOUMAYA.ACTIVITE
SET DEFINE OFF;
Insert into SOUMAYA.ACTIVITE (ID,NOM_ACTIVITE,DAT,DUREE,TYPE) values ('1','delic','01/01/2000 00:00','15','89');
Insert into SOUMAYA.ACTIVITE (ID,NOM_ACTIVITE,DAT,DUREE,TYPE) values ('0','amar','01/01/2000 00:00','15','89');
Insert into SOUMAYA.ACTIVITE (ID,NOM_ACTIVITE,DAT,DUREE,TYPE) values ('5','azaz','01/01/2000 00:00','2','5');
Insert into SOUMAYA.ACTIVITE (ID,NOM_ACTIVITE,DAT,DUREE,TYPE) values ('2','azaz','01/01/2000 00:00','2','5');
Insert into SOUMAYA.ACTIVITE (ID,NOM_ACTIVITE,DAT,DUREE,TYPE) values ('3','azaz','01/01/2000 00:00','2','5');
Insert into SOUMAYA.ACTIVITE (ID,NOM_ACTIVITE,DAT,DUREE,TYPE) values ('4','samir','01/01/2000 00:00','45','15');
REM INSERTING into SOUMAYA.ANIMAL
SET DEFINE OFF;
Insert into SOUMAYA.ANIMAL (ID,AGE,PRIX,NOM,RACE,SEX,DATE_ACHAT) values ('8','12','12','az','az','az','01/01/2000');
REM INSERTING into SOUMAYA.BOUTIQUE
SET DEFINE OFF;
Insert into SOUMAYA.BOUTIQUE (ID,NOM,ADR,TEL,MAIL) values ('121','121','2121','2121','212');
Insert into SOUMAYA.BOUTIQUE (ID,NOM,ADR,TEL,MAIL) values ('12212121','212121','212121','212121','211221');
REM INSERTING into SOUMAYA.ENFANT
SET DEFINE OFF;
Insert into SOUMAYA.ENFANT (ID,NOM_PRENOM,ETAT_PSYCOLOGIQUE,TALENT,SEXE) values ('2','5','5','25','2');
REM INSERTING into SOUMAYA.ETUDIANT
SET DEFINE OFF;
Insert into SOUMAYA.ETUDIANT (ID,NOM,PRENOM) values ('123','azizz','z');
REM INSERTING into SOUMAYA.FICHE_ANIMAL
SET DEFINE OFF;
Insert into SOUMAYA.FICHE_ANIMAL (ID,POID,TAILLE,NBR_CONSULTATION,ID_ANNIMAL,DATE_VACC,ETAT,NOM_MALADE) values ('15','23','12','21','21','01/01/2000','az','za');
Insert into SOUMAYA.FICHE_ANIMAL (ID,POID,TAILLE,NBR_CONSULTATION,ID_ANNIMAL,DATE_VACC,ETAT,NOM_MALADE) values ('123','23','12','21','21','01/01/2000','az','za');
Insert into SOUMAYA.FICHE_ANIMAL (ID,POID,TAILLE,NBR_CONSULTATION,ID_ANNIMAL,DATE_VACC,ETAT,NOM_MALADE) values ('12','25','2','2','2552','01/01/2000','25','52');
REM INSERTING into SOUMAYA.FOURNITURE
SET DEFINE OFF;
Insert into SOUMAYA.FOURNITURE (ID,REF,QUANTITE,PRIX,DAT) values ('1','1','1','1','01/01/2000');
Insert into SOUMAYA.FOURNITURE (ID,REF,QUANTITE,PRIX,DAT) values ('4','9','195','20','08/12/2028');
Insert into SOUMAYA.FOURNITURE (ID,REF,QUANTITE,PRIX,DAT) values ('2','15','350','150','08/12/2000');
Insert into SOUMAYA.FOURNITURE (ID,REF,QUANTITE,PRIX,DAT) values ('3','25','1950','120','08/12/2028');
Insert into SOUMAYA.FOURNITURE (ID,REF,QUANTITE,PRIX,DAT) values ('8','36','25','958','08/12/2028');
Insert into SOUMAYA.FOURNITURE (ID,REF,QUANTITE,PRIX,DAT) values ('5','19','1950','120','08/12/2028');
REM INSERTING into SOUMAYA.INGR
SET DEFINE OFF;
Insert into SOUMAYA.INGR (NOMING,TYPE,VALEUR_ALIMENTAIRE) values ('1','1','1');
Insert into SOUMAYA.INGR (NOMING,TYPE,VALEUR_ALIMENTAIRE) values ('2','2','2');
Insert into SOUMAYA.INGR (NOMING,TYPE,VALEUR_ALIMENTAIRE) values ('3','3','3');
Insert into SOUMAYA.INGR (NOMING,TYPE,VALEUR_ALIMENTAIRE) values ('123','123','123');
REM INSERTING into SOUMAYA.INGREDIENT
SET DEFINE OFF;
Insert into SOUMAYA.INGREDIENT (NOM_R,TYPE_R,HEURE_R,CATEGORIE_R) values ('1','1','1','1');
Insert into SOUMAYA.INGREDIENT (NOM_R,TYPE_R,HEURE_R,CATEGORIE_R) values ('2','2','2','2');
REM INSERTING into SOUMAYA.MEDICAMENT
SET DEFINE OFF;
Insert into SOUMAYA.MEDICAMENT (ID,QUANTITE,DAT,PRIX) values ('5','12','01/01/2000','100');
Insert into SOUMAYA.MEDICAMENT (ID,QUANTITE,DAT,PRIX) values ('6','35','01/01/2000','35');
Insert into SOUMAYA.MEDICAMENT (ID,QUANTITE,DAT,PRIX) values ('9','12','01/01/2222','12');
Insert into SOUMAYA.MEDICAMENT (ID,QUANTITE,DAT,PRIX) values ('2','12','01/01/2000','12');
Insert into SOUMAYA.MEDICAMENT (ID,QUANTITE,DAT,PRIX) values ('15','12','01/01/2000','100');
REM INSERTING into SOUMAYA.PRESTATAIRE
SET DEFINE OFF;
Insert into SOUMAYA.PRESTATAIRE (IDPRES,NOMPRES,PRENOMPRES,SALAIREPRES,SPECIALITEPRES,DATEEMBAUCHEPRES,NBR_HEURESPRES,TELPRES,ADRESSEPRES,SEXEPRES) values ('1','1','11','1','1','1','1','1','1','1');
REM INSERTING into SOUMAYA.SUIVI
SET DEFINE OFF;
Insert into SOUMAYA.SUIVI (ID,TAILLE,POID,TENSION,DAT) values ('2','22','22','2','01/01/2000 00:00');
Insert into SOUMAYA.SUIVI (ID,TAILLE,POID,TENSION,DAT) values ('3','3','3','23','01/01/2000 00:00');
Insert into SOUMAYA.SUIVI (ID,TAILLE,POID,TENSION,DAT) values ('5','5','5','5','01/01/2000 00:00');
Insert into SOUMAYA.SUIVI (ID,TAILLE,POID,TENSION,DAT) values ('6','6','6','6','01/01/2000 00:00');
Insert into SOUMAYA.SUIVI (ID,TAILLE,POID,TENSION,DAT) values ('10','11','11','12','09/03/2010 00:00');
Insert into SOUMAYA.SUIVI (ID,TAILLE,POID,TENSION,DAT) values ('12','11','11','12','11/01/2010 00:00');
Insert into SOUMAYA.SUIVI (ID,TAILLE,POID,TENSION,DAT) values ('1','1','1','1','01/01/2000 00:00');
REM INSERTING into SOUMAYA.VETEMENT
SET DEFINE OFF;
Insert into SOUMAYA.VETEMENT (REF,SAISON,GENRE,TYPE,TAILLE,MARQUE,PRIX) values ('12','121','21212','1212','1212212','212121','2112');
Insert into SOUMAYA.VETEMENT (REF,SAISON,GENRE,TYPE,TAILLE,MARQUE,PRIX) values ('0','000000','000','0000','00','000','0');
--------------------------------------------------------
--  DDL for Index ACTIVITE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SOUMAYA"."ACTIVITE_PK" ON "SOUMAYA"."ACTIVITE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ANIMAL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SOUMAYA"."ANIMAL_PK" ON "SOUMAYA"."ANIMAL" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index BOUTIQUE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SOUMAYA"."BOUTIQUE_PK" ON "SOUMAYA"."BOUTIQUE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ENFANT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SOUMAYA"."ENFANT_PK" ON "SOUMAYA"."ENFANT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index FICHE_ANIMAL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SOUMAYA"."FICHE_ANIMAL_PK" ON "SOUMAYA"."FICHE_ANIMAL" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index FOURNITURE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SOUMAYA"."FOURNITURE_PK" ON "SOUMAYA"."FOURNITURE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index INGR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SOUMAYA"."INGR_PK" ON "SOUMAYA"."INGR" ("NOMING") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TABLE1_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SOUMAYA"."TABLE1_PK" ON "SOUMAYA"."INGREDIENT" ("NOM_R") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index MEDICAMENT_INDEX1
--------------------------------------------------------

  CREATE INDEX "SOUMAYA"."MEDICAMENT_INDEX1" ON "SOUMAYA"."MEDICAMENT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PRESTATAIRE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SOUMAYA"."PRESTATAIRE_PK" ON "SOUMAYA"."PRESTATAIRE" ("IDPRES") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "SOUMAYA"."ID" ON "SOUMAYA"."SUIVI" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index VETEMENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SOUMAYA"."VETEMENT_PK" ON "SOUMAYA"."VETEMENT" ("REF") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger SUIVI_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SOUMAYA"."SUIVI_TRG" 
BEFORE INSERT ON SUIVI 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SOUMAYA"."SUIVI_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table ACTIVITE
--------------------------------------------------------

  ALTER TABLE "SOUMAYA"."ACTIVITE" ADD CONSTRAINT "ACTIVITE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SOUMAYA"."ACTIVITE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ANIMAL
--------------------------------------------------------

  ALTER TABLE "SOUMAYA"."ANIMAL" ADD CONSTRAINT "ANIMAL_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SOUMAYA"."ANIMAL" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BOUTIQUE
--------------------------------------------------------

  ALTER TABLE "SOUMAYA"."BOUTIQUE" ADD CONSTRAINT "BOUTIQUE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SOUMAYA"."BOUTIQUE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ENFANT
--------------------------------------------------------

  ALTER TABLE "SOUMAYA"."ENFANT" ADD CONSTRAINT "ENFANT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SOUMAYA"."ENFANT" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FICHE_ANIMAL
--------------------------------------------------------

  ALTER TABLE "SOUMAYA"."FICHE_ANIMAL" ADD CONSTRAINT "FICHE_ANIMAL_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SOUMAYA"."FICHE_ANIMAL" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FOURNITURE
--------------------------------------------------------

  ALTER TABLE "SOUMAYA"."FOURNITURE" ADD CONSTRAINT "FOURNITURE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SOUMAYA"."FOURNITURE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table INGR
--------------------------------------------------------

  ALTER TABLE "SOUMAYA"."INGR" ADD CONSTRAINT "INGR_PK" PRIMARY KEY ("NOMING")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SOUMAYA"."INGR" MODIFY ("NOMING" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table INGREDIENT
--------------------------------------------------------

  ALTER TABLE "SOUMAYA"."INGREDIENT" ADD CONSTRAINT "TABLE1_PK" PRIMARY KEY ("NOM_R")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SOUMAYA"."INGREDIENT" MODIFY ("NOM_R" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MEDICAMENT
--------------------------------------------------------

  ALTER TABLE "SOUMAYA"."MEDICAMENT" ADD CONSTRAINT "PK_ID" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRESTATAIRE
--------------------------------------------------------

  ALTER TABLE "SOUMAYA"."PRESTATAIRE" ADD CONSTRAINT "PRESTATAIRE_PK" PRIMARY KEY ("IDPRES")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SOUMAYA"."PRESTATAIRE" MODIFY ("IDPRES" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SUIVI
--------------------------------------------------------

  ALTER TABLE "SOUMAYA"."SUIVI" ADD CONSTRAINT "ID" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SOUMAYA"."SUIVI" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table VETEMENT
--------------------------------------------------------

  ALTER TABLE "SOUMAYA"."VETEMENT" ADD CONSTRAINT "VETEMENT_PK" PRIMARY KEY ("REF")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SOUMAYA"."VETEMENT" MODIFY ("REF" NOT NULL ENABLE);
